/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VseRulesRouteImport } from './routes/vse-rules'
import { Route as ScmRulesRouteImport } from './routes/scm-rules'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const VseRulesRoute = VseRulesRouteImport.update({
  id: '/vse-rules',
  path: '/vse-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ScmRulesRoute = ScmRulesRouteImport.update({
  id: '/scm-rules',
  path: '/scm-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/scm-rules': typeof ScmRulesRoute
  '/vse-rules': typeof VseRulesRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/scm-rules': typeof ScmRulesRoute
  '/vse-rules': typeof VseRulesRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/scm-rules': typeof ScmRulesRoute
  '/vse-rules': typeof VseRulesRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/scm-rules' | '/vse-rules' | '/events/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/scm-rules' | '/vse-rules' | '/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/scm-rules'
    | '/vse-rules'
    | '/events/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ScmRulesRoute: typeof ScmRulesRoute
  VseRulesRoute: typeof VseRulesRoute
  EventsSlugRoute: typeof EventsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vse-rules': {
      id: '/vse-rules'
      path: '/vse-rules'
      fullPath: '/vse-rules'
      preLoaderRoute: typeof VseRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scm-rules': {
      id: '/scm-rules'
      path: '/scm-rules'
      fullPath: '/scm-rules'
      preLoaderRoute: typeof ScmRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ScmRulesRoute: ScmRulesRoute,
  VseRulesRoute: VseRulesRoute,
  EventsSlugRoute: EventsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
