/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VseRulesRouteImport } from './routes/vse-rules'
import { Route as TriviaRulesRouteImport } from './routes/trivia-rules'
import { Route as ScmRulesRouteImport } from './routes/scm-rules'
import { Route as PdRulesRouteImport } from './routes/pd-rules'
import { Route as CrisisRulesRouteImport } from './routes/crisis-rules'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const VseRulesRoute = VseRulesRouteImport.update({
  id: '/vse-rules',
  path: '/vse-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const TriviaRulesRoute = TriviaRulesRouteImport.update({
  id: '/trivia-rules',
  path: '/trivia-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ScmRulesRoute = ScmRulesRouteImport.update({
  id: '/scm-rules',
  path: '/scm-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PdRulesRoute = PdRulesRouteImport.update({
  id: '/pd-rules',
  path: '/pd-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisisRulesRoute = CrisisRulesRouteImport.update({
  id: '/crisis-rules',
  path: '/crisis-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crisis-rules': typeof CrisisRulesRoute
  '/pd-rules': typeof PdRulesRoute
  '/scm-rules': typeof ScmRulesRoute
  '/trivia-rules': typeof TriviaRulesRoute
  '/vse-rules': typeof VseRulesRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crisis-rules': typeof CrisisRulesRoute
  '/pd-rules': typeof PdRulesRoute
  '/scm-rules': typeof ScmRulesRoute
  '/trivia-rules': typeof TriviaRulesRoute
  '/vse-rules': typeof VseRulesRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crisis-rules': typeof CrisisRulesRoute
  '/pd-rules': typeof PdRulesRoute
  '/scm-rules': typeof ScmRulesRoute
  '/trivia-rules': typeof TriviaRulesRoute
  '/vse-rules': typeof VseRulesRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/crisis-rules'
    | '/pd-rules'
    | '/scm-rules'
    | '/trivia-rules'
    | '/vse-rules'
    | '/events/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/crisis-rules'
    | '/pd-rules'
    | '/scm-rules'
    | '/trivia-rules'
    | '/vse-rules'
    | '/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/crisis-rules'
    | '/pd-rules'
    | '/scm-rules'
    | '/trivia-rules'
    | '/vse-rules'
    | '/events/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CrisisRulesRoute: typeof CrisisRulesRoute
  PdRulesRoute: typeof PdRulesRoute
  ScmRulesRoute: typeof ScmRulesRoute
  TriviaRulesRoute: typeof TriviaRulesRoute
  VseRulesRoute: typeof VseRulesRoute
  EventsSlugRoute: typeof EventsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vse-rules': {
      id: '/vse-rules'
      path: '/vse-rules'
      fullPath: '/vse-rules'
      preLoaderRoute: typeof VseRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trivia-rules': {
      id: '/trivia-rules'
      path: '/trivia-rules'
      fullPath: '/trivia-rules'
      preLoaderRoute: typeof TriviaRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scm-rules': {
      id: '/scm-rules'
      path: '/scm-rules'
      fullPath: '/scm-rules'
      preLoaderRoute: typeof ScmRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pd-rules': {
      id: '/pd-rules'
      path: '/pd-rules'
      fullPath: '/pd-rules'
      preLoaderRoute: typeof PdRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crisis-rules': {
      id: '/crisis-rules'
      path: '/crisis-rules'
      fullPath: '/crisis-rules'
      preLoaderRoute: typeof CrisisRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CrisisRulesRoute: CrisisRulesRoute,
  PdRulesRoute: PdRulesRoute,
  ScmRulesRoute: ScmRulesRoute,
  TriviaRulesRoute: TriviaRulesRoute,
  VseRulesRoute: VseRulesRoute,
  EventsSlugRoute: EventsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
